name       : wine-nine-standalone
version    : 0.4
release    : 1
source     :
    - https://github.com/iXit/wine-nine-standalone/archive/v0.4.tar.gz : 7636572d4b823562a5c587ac61e4a1e2534fdc151dbf94fa37563afe6e082d4f
license    : LGPL-2.1-or-later
component  : virt
summary    : Gallium Nine Standalone
description: |
    Gallium Nine allows to run any Direct3D 9 application with nearly no CPU overhead, which provides a smoother gaming experience and increased FPS.

    Gallium Nine Standalone, as the name implies, is a standalone version of the WINE parts of Gallium Nine.

    This decouples Gallium Nine from the WINE tree, so that it can be used with any WINE version. There is no need for any WINE patches. A stable, development, or staging WINE release is sufficient.
builddeps  :
    - pkgconfig32(d3d)
    - wine-32bit-devel
emul32     : yes
setup      : |
    %patch -p1 < $pkgfiles/0001-bootstrap-add-solus.patch

    ./bootstrap.sh

    %meson_configure \
        --cross-file "tools/cross-wine%LIBSUFFIX%" \
        --buildtype "release"
build      : |
    %ninja_build
install    : |
    %ninja_install
