name       : wine-nine-standalone
version    : '0.6'
release    : 5
source     :
    - https://github.com/iXit/wine-nine-standalone/archive/v0.6.tar.gz : 2fa595b63947d2c8b3de6a0a4ada891dc16f791c623c0b32ee38a7580371bba3
license    : LGPL-2.1-or-later
component  : virt
summary    : Gallium Nine Standalone
description: |
    Gallium Nine allows to run any Direct3D 9 application with nearly no CPU overhead, which provides a smoother gaming experience and increased FPS.

    Gallium Nine Standalone, as the name implies, is a standalone version of the WINE parts of Gallium Nine.

    This decouples Gallium Nine from the WINE tree, so that it can be used with any WINE version. There is no need for any WINE patches. A stable, development, or staging WINE release is sufficient.
builddeps  :
    - pkgconfig32(d3d)
    - pkgconfig32(x11)
    - wine-32bit-devel
emul32     : yes
setup      : |
    ./bootstrap.sh

    %meson_configure \
        --cross-file "tools/cross-wine%LIBSUFFIX%" \
        --buildtype "release"
build      : |
    %ninja_build
install    : |
    pushd solusBuildDir
        install -m00755 -d $installdir/%libdir%/wine
        install -m00755 -d $installdir/%libdir%/wine/fakedlls

        install -m00755 ./ninewinecfg/ninewinecfg.exe.so $installdir/%libdir%/wine/ninewinecfg.exe.so
        install -m00755 ./ninewinecfg/ninewinecfg.exe.fake $installdir/%libdir%/wine/fakedlls/ninewinecfg.exe

        install -m00755 ./d3d9-nine/d3d9-nine.dll.so $installdir/%libdir%/wine/d3d9-nine.dll.so
        install -m00755 ./d3d9-nine/d3d9-nine.dll.fake $installdir/%libdir%/wine/fakedlls/d3d9-nine.dll
    popd
